// <auto-generated />
using System;
using ECIMS.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECIMS.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260717112658_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ECIMS.Web.Models.Entities.AcceptanceCert", b =>
                {
                    b.Property<int>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CertificateId"));

                    b.Property<int>("AttemptId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PdfFilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CertificateId");

                    b.HasIndex("AttemptId")
                        .IsUnique();

                    b.ToTable("AcceptanceCerts");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.CompanyStampAsset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AssetId"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UploadedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("AssetId");

                    b.HasIndex("UploadedById");

                    b.ToTable("CompanyStampAssets");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("CustomerId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CustomerName")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.CustomerBranch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("SiteContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SiteContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("BranchId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CustomerId", "BranchName")
                        .IsUnique();

                    b.ToTable("CustomerBranches");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.DigitalSignature", b =>
                {
                    b.Property<int>("SignatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SignatureId"));

                    b.Property<int>("AttemptId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateStamped")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OriginalSignatureBlob")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<sbyte>("SignatoryRole")
                        .HasColumnType("tinyint");

                    b.Property<int>("SignedById")
                        .HasColumnType("int");

                    b.HasKey("SignatureId");

                    b.HasIndex("SignedById");

                    b.HasIndex("AttemptId", "SignatoryRole")
                        .IsUnique();

                    b.ToTable("DigitalSignatures");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("ConsultantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProjectManagerId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("ProjectId");

                    b.HasIndex("BranchId");

                    b.HasIndex("ConsultantId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectManagerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.ProjectUatAttempt", b =>
                {
                    b.Property<int>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AttemptId"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<int>("InitiatedById")
                        .HasColumnType("int");

                    b.Property<sbyte>("OverallStatus")
                        .HasColumnType("tinyint");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("AttemptId");

                    b.HasIndex("InitiatedById");

                    b.HasIndex("ProjectId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("ProjectUatAttempts");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.ProjectUatResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<int>("AttemptId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<string>("EvidencePath")
                        .HasColumnType("longtext");

                    b.Property<int>("ExecutedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExecutedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.Property<sbyte?>("LastModifiedByRole")
                        .HasColumnType("tinyint");

                    b.Property<int>("MasterItemId")
                        .HasColumnType("int");

                    b.Property<sbyte>("PassStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("ResultId");

                    b.HasIndex("ExecutedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("MasterItemId");

                    b.HasIndex("AttemptId", "MasterItemId")
                        .IsUnique();

                    b.ToTable("ProjectUatResults");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.ProjectUatResultHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("EditComment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EditedById")
                        .HasColumnType("int");

                    b.Property<sbyte>("PostEditPassStatus")
                        .HasColumnType("tinyint");

                    b.Property<sbyte>("PreEditPassStatus")
                        .HasColumnType("tinyint");

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.HasIndex("EditedById");

                    b.HasIndex("ResultId");

                    b.ToTable("ProjectUatResultHistories");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.UatMasterItem", b =>
                {
                    b.Property<int>("MasterItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MasterItemId"));

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("TestDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MasterItemId");

                    b.HasIndex("SectionId");

                    b.ToTable("UatMasterItems");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.UatSection", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SectionId");

                    b.ToTable("UatSections");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.AcceptanceCert", b =>
                {
                    b.HasOne("ECIMS.Web.Models.Entities.ProjectUatAttempt", "Attempt")
                        .WithOne("Certificate")
                        .HasForeignKey("ECIMS.Web.Models.Entities.AcceptanceCert", "AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.CompanyStampAsset", b =>
                {
                    b.HasOne("ECIMS.Web.Models.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.Customer", b =>
                {
                    b.HasOne("ECIMS.Web.Models.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.CustomerBranch", b =>
                {
                    b.HasOne("ECIMS.Web.Models.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECIMS.Web.Models.Entities.Customer", "Customer")
                        .WithMany("Branches")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.DigitalSignature", b =>
                {
                    b.HasOne("ECIMS.Web.Models.Entities.ProjectUatAttempt", "Attempt")
                        .WithMany("Signatures")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECIMS.Web.Models.Entities.User", "SignedBy")
                        .WithMany()
                        .HasForeignKey("SignedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("SignedBy");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.Project", b =>
                {
                    b.HasOne("ECIMS.Web.Models.Entities.CustomerBranch", "Branch")
                        .WithMany("Projects")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECIMS.Web.Models.Entities.User", "Consultant")
                        .WithMany()
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECIMS.Web.Models.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECIMS.Web.Models.Entities.User", "ProjectManager")
                        .WithMany()
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Consultant");

                    b.Navigation("CreatedBy");

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.ProjectUatAttempt", b =>
                {
                    b.HasOne("ECIMS.Web.Models.Entities.User", "InitiatedBy")
                        .WithMany()
                        .HasForeignKey("InitiatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECIMS.Web.Models.Entities.Project", "Project")
                        .WithMany("Attempts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InitiatedBy");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.ProjectUatResult", b =>
                {
                    b.HasOne("ECIMS.Web.Models.Entities.ProjectUatAttempt", "Attempt")
                        .WithMany("Results")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECIMS.Web.Models.Entities.User", "ExecutedBy")
                        .WithMany()
                        .HasForeignKey("ExecutedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECIMS.Web.Models.Entities.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ECIMS.Web.Models.Entities.UatMasterItem", "MasterItem")
                        .WithMany()
                        .HasForeignKey("MasterItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("ExecutedBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("MasterItem");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.ProjectUatResultHistory", b =>
                {
                    b.HasOne("ECIMS.Web.Models.Entities.User", "EditedBy")
                        .WithMany()
                        .HasForeignKey("EditedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECIMS.Web.Models.Entities.ProjectUatResult", "Result")
                        .WithMany("History")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EditedBy");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.UatMasterItem", b =>
                {
                    b.HasOne("ECIMS.Web.Models.Entities.UatSection", "Section")
                        .WithMany("MasterItems")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.User", b =>
                {
                    b.HasOne("ECIMS.Web.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.Customer", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.CustomerBranch", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.Project", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.ProjectUatAttempt", b =>
                {
                    b.Navigation("Certificate");

                    b.Navigation("Results");

                    b.Navigation("Signatures");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.ProjectUatResult", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ECIMS.Web.Models.Entities.UatSection", b =>
                {
                    b.Navigation("MasterItems");
                });
#pragma warning restore 612, 618
        }
    }
}
